version: '3'

services:
  datastore:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    networks:
      - backend
    volumes:
      - ../datastore/data/postgres:/var/lib/postgresql
    environment:
      POSTGRES_USER: ebs_dev
      POSTGRES_PASSWORD: Ebs@5432
      POSTGRES_DB: salinization_datastore

networks:
  backend:
    driver: bridge